apiVersion: v1
kind: Service
metadata:
  name: noteflow-service
  labels:
    app: noteflow
spec:
  type: NodePort
  selector:
    app: noteflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500
